import Case from "../models/Case.js";
import Evidence from "../models/Evidence.js";

/**
 * Create a new case
 * POST /api/cases
 */
const createCase = async (req, res) => {
  try {
    const {
      title,
      description,
      caseType,
      priority,
      assignedInvestigators,
      tags,
      metadata,
    } = req.body;

    // NOTE: caseNumber is intentionally NOT extracted from req.body
    // It will be auto-generated by the schema pre-validate hook

    // Validation
    if (!title || title.trim() === "") {
      return res.status(400).json({
        success: false,
        message: "Case title is required",
      });
    }

    if (!description || description.trim() === "") {
      return res.status(400).json({
        success: false,
        message: "Case description is required",
      });
    }

    if (!caseType) {
      return res.status(400).json({
        success: false,
        message: "Case type is required",
      });
    }

    // Validate case type
    const validCaseTypes = ["criminal", "civil", "corporate", "cyber", "other"];
    if (!validCaseTypes.includes(caseType)) {
      return res.status(400).json({
        success: false,
        message: `Invalid case type. Must be one of: ${validCaseTypes.join(", ")}`,
      });
    }

    // Create case (caseNumber will be auto-generated)
    const newCase = await Case.create({
      title: title.trim(),
      description: description.trim(),
      caseType,
      priority: priority || "medium",
      leadInvestigator: req.user.id, // From auth middleware
      assignedInvestigators: assignedInvestigators || [],
      tags: tags || [],
      metadata: metadata || {},
      // DO NOT include caseNumber here - let the schema generate it
    });

    console.log("✅ Case created:", newCase.caseNumber);

    // Add initial timeline entry
    newCase.timeline.push({
      event: "Case Created",
      date: new Date(),
      description: `Case created by ${req.user.username}`,
      recordedBy: req.user.id,
    });

    await newCase.save();

    // Populate user references before sending response
    await newCase.populate("leadInvestigator", "username email role");
    await newCase.populate("assignedInvestigators", "username email role");

    res.status(201).json({
      success: true,
      message: "Case created successfully",
      data: newCase,
    });
  } catch (error) {
    console.error("❌ Create case error:", error);
    res.status(500).json({
      success: false,
      message: "Error creating case",
      error: error.message,
    });
  }
};

/**
 * Get all cases
 * GET /api/cases
 * Query params: status, caseType, priority, search
 */
const getAllCases = async (req, res) => {
  try {
    const {
      status,
      caseType,
      priority,
      search,
      limit = 50,
      page = 1,
    } = req.query;

    // Build filter
    const filter = {};

    if (status) {
      filter.status = status;
    }

    if (caseType) {
      filter.caseType = caseType;
    }

    if (priority) {
      filter.priority = priority;
    }

    // Search in title and description
    if (search) {
      filter.$or = [
        { title: { $regex: search, $options: "i" } },
        { description: { $regex: search, $options: "i" } },
        { caseNumber: { $regex: search, $options: "i" } },
      ];
    }

    // Calculate pagination
    const skip = (parseInt(page) - 1) * parseInt(limit);

    // Get total count for pagination
    const totalCases = await Case.countDocuments(filter);

    // Get cases with pagination
    const cases = await Case.find(filter)
      .populate("leadInvestigator", "username email role")
      .populate("assignedInvestigators", "username email role")
      .populate("evidence", "evidenceId fileName ipfsHash status")
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      count: cases.length,
      total: totalCases,
      page: parseInt(page),
      totalPages: Math.ceil(totalCases / parseInt(limit)),
      data: cases,
    });
  } catch (error) {
    console.error("❌ Get all cases error:", error);
    res.status(500).json({
      success: false,
      message: "Error retrieving cases",
      error: error.message,
    });
  }
};

/**
 * Get single case by ID
 * GET /api/cases/:id
 */
const getCaseById = async (req, res) => {
  try {
    const caseData = await Case.findById(req.params.id)
      .populate("leadInvestigator", "username email role walletAddress")
      .populate("assignedInvestigators", "username email role")
      .populate({
        path: "evidence",
        select:
          "evidenceId fileName fileType fileSize ipfsHash fileHash status createdAt",
        options: { sort: { createdAt: -1 } },
      })
      .populate("relatedCases.caseId", "caseNumber title status")
      .populate("timeline.recordedBy", "username");

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    res.status(200).json({
      success: true,
      data: caseData,
    });
  } catch (error) {
    console.error("❌ Get case error:", error);

    // Handle invalid ObjectId
    if (error.kind === "ObjectId") {
      return res.status(404).json({
        success: false,
        message: "Case not found - invalid ID format",
      });
    }

    res.status(500).json({
      success: false,
      message: "Error retrieving case",
      error: error.message,
    });
  }
};

/**
 * Find similar cases
 * GET /api/cases/analyze/similar/:id
 */
const findSimilarCases = async (req, res) => {
  try {
    const currentCase = await Case.findById(req.params.id);

    if (!currentCase) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    // Build similarity criteria
    const similarityFilters = [];

    // 1. Same case type
    similarityFilters.push({
      caseType: currentCase.caseType,
      _id: { $ne: currentCase._id },
    });

    // 2. Matching tags
    if (currentCase.tags && currentCase.tags.length > 0) {
      similarityFilters.push({
        tags: { $in: currentCase.tags },
        _id: { $ne: currentCase._id },
      });
    }

    // 3. Same location
    if (currentCase.metadata?.location) {
      similarityFilters.push({
        "metadata.location": currentCase.metadata.location,
        _id: { $ne: currentCase._id },
      });
    }

    // 4. Similar incident timeframe (within 30 days)
    if (currentCase.metadata?.incidentDate) {
      const incidentDate = new Date(currentCase.metadata.incidentDate);
      const dateRange = 30 * 24 * 60 * 60 * 1000;

      similarityFilters.push({
        "metadata.incidentDate": {
          $gte: new Date(incidentDate.getTime() - dateRange),
          $lte: new Date(incidentDate.getTime() + dateRange),
        },
        _id: { $ne: currentCase._id },
      });
    }

    // Find similar cases
    const similarCases = await Case.find({
      $or: similarityFilters,
    })
      .populate("leadInvestigator", "username email")
      .populate("evidence", "evidenceId fileName")
      .select(
        "caseNumber title caseType status priority metadata tags createdAt",
      )
      .sort({ createdAt: -1 })
      .limit(10);

    // Calculate similarity scores
    const casesWithScores = similarCases.map((similarCase) => {
      let score = 0;
      const reasons = [];

      if (similarCase.caseType === currentCase.caseType) {
        score += 3;
        reasons.push("Same case type");
      }

      if (currentCase.tags && similarCase.tags) {
        const matchingTags = currentCase.tags.filter((tag) =>
          similarCase.tags.includes(tag),
        );
        if (matchingTags.length > 0) {
          score += matchingTags.length * 2;
          reasons.push(`${matchingTags.length} matching tag(s)`);
        }
      }

      if (
        currentCase.metadata?.location &&
        similarCase.metadata?.location === currentCase.metadata?.location
      ) {
        score += 4;
        reasons.push("Same location");
      }

      if (
        currentCase.metadata?.incidentDate &&
        similarCase.metadata?.incidentDate
      ) {
        const timeDiff = Math.abs(
          new Date(currentCase.metadata.incidentDate) -
            new Date(similarCase.metadata.incidentDate),
        );
        const daysDiff = timeDiff / (1000 * 60 * 60 * 24);

        if (daysDiff <= 30) {
          score += 2;
          reasons.push(`Incident within ${Math.round(daysDiff)} days`);
        }
      }

      return {
        ...similarCase.toObject(),
        similarityScore: score,
        similarityReasons: reasons,
      };
    });

    casesWithScores.sort((a, b) => b.similarityScore - a.similarityScore);
    const relevantCases = casesWithScores.filter((c) => c.similarityScore >= 2);

    res.status(200).json({
      success: true,
      count: relevantCases.length,
      currentCase: {
        id: currentCase._id,
        caseNumber: currentCase.caseNumber,
        title: currentCase.title,
      },
      data: relevantCases,
    });
  } catch (error) {
    console.error("❌ Find similar cases error:", error);

    if (error.kind === "ObjectId") {
      return res.status(404).json({
        success: false,
        message: "Case not found - invalid ID format",
      });
    }

    res.status(500).json({
      success: false,
      message: "Error finding similar cases",
      error: error.message,
    });
  }
};

/**
 * Update case
 * PUT /api/cases/:id
 */
const updateCase = async (req, res) => {
  try {
    const {
      title,
      description,
      status,
      priority,
      assignedInvestigators,
      tags,
      metadata,
    } = req.body;

    // NOTE: caseNumber is NOT accepted for updates - it's immutable

    const caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    // Update fields if provided
    if (title) caseData.title = title.trim();
    if (description) caseData.description = description.trim();
    if (status) caseData.status = status;
    if (priority) caseData.priority = priority;
    if (assignedInvestigators)
      caseData.assignedInvestigators = assignedInvestigators;
    if (tags) caseData.tags = tags;
    if (metadata) caseData.metadata = { ...caseData.metadata, ...metadata };

    // Add timeline entry
    caseData.timeline.push({
      event: "Case Updated",
      date: new Date(),
      description: `Case updated by ${req.user.username}`,
      recordedBy: req.user.id,
    });

    await caseData.save();

    await caseData.populate("leadInvestigator", "username email");
    await caseData.populate("assignedInvestigators", "username email");

    res.status(200).json({
      success: true,
      message: "Case updated successfully",
      data: caseData,
    });
  } catch (error) {
    console.error("❌ Update case error:", error);
    res.status(500).json({
      success: false,
      message: "Error updating case",
      error: error.message,
    });
  }
};

/**
 * Close case
 * PUT /api/cases/:id/close
 */
const closeCase = async (req, res) => {
  try {
    const { findings } = req.body;

    const caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    if (caseData.status === "closed") {
      return res.status(400).json({
        success: false,
        message: "Case is already closed",
      });
    }

    caseData.status = "closed";
    caseData.metadata.closedDate = new Date();

    caseData.timeline.push({
      event: "Case Closed",
      date: new Date(),
      description: findings || `Case closed by ${req.user.username}`,
      recordedBy: req.user.id,
    });

    await caseData.save();

    res.status(200).json({
      success: true,
      message: "Case closed successfully",
      data: caseData,
    });
  } catch (error) {
    console.error("❌ Close case error:", error);
    res.status(500).json({
      success: false,
      message: "Error closing case",
      error: error.message,
    });
  }
};

/**
 * Add timeline entry
 * POST /api/cases/:id/timeline
 */
const addTimelineEntry = async (req, res) => {
  try {
    const { event, description } = req.body;

    if (!event || !description) {
      return res.status(400).json({
        success: false,
        message: "Event and description are required",
      });
    }

    const caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    caseData.timeline.push({
      event: event.trim(),
      date: new Date(),
      description: description.trim(),
      recordedBy: req.user.id,
    });

    await caseData.save();

    res.status(200).json({
      success: true,
      message: "Timeline entry added",
      data: caseData.timeline[caseData.timeline.length - 1],
    });
  } catch (error) {
    console.error("❌ Add timeline entry error:", error);
    res.status(500).json({
      success: false,
      message: "Error adding timeline entry",
      error: error.message,
    });
  }
};

/**
 * Link evidence to case
 * POST /api/cases/:id/evidence/:evidenceId
 */
const linkEvidence = async (req, res) => {
  try {
    const { id: caseId, evidenceId } = req.params;

    const caseData = await Case.findById(caseId);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: "Case not found",
      });
    }

    const evidence = await Evidence.findById(evidenceId);

    if (!evidence) {
      return res.status(404).json({
        success: false,
        message: "Evidence not found",
      });
    }

    if (caseData.evidence.includes(evidenceId)) {
      return res.status(400).json({
        success: false,
        message: "Evidence already linked to this case",
      });
    }

    caseData.evidence.push(evidenceId);
    evidence.caseId = caseData.caseNumber;
    await evidence.save();

    caseData.timeline.push({
      event: "Evidence Linked",
      date: new Date(),
      description: `Evidence ${evidence.evidenceId} linked to case`,
      recordedBy: req.user.id,
    });

    await caseData.save();

    res.status(200).json({
      success: true,
      message: "Evidence linked successfully",
      data: {
        caseNumber: caseData.caseNumber,
        evidenceId: evidence.evidenceId,
      },
    });
  } catch (error) {
    console.error("❌ Link evidence error:", error);
    res.status(500).json({
      success: false,
      message: "Error linking evidence",
      error: error.message,
    });
  }
};

/**
 * Get case statistics
 * GET /api/cases/stats
 */
const getCaseStats = async (req, res) => {
  try {
    const stats = {
      total: await Case.countDocuments(),
      byStatus: {
        open: await Case.countDocuments({ status: "open" }),
        inProgress: await Case.countDocuments({ status: "in-progress" }),
        closed: await Case.countDocuments({ status: "closed" }),
        archived: await Case.countDocuments({ status: "archived" }),
      },
      byType: {
        criminal: await Case.countDocuments({ caseType: "criminal" }),
        civil: await Case.countDocuments({ caseType: "civil" }),
        corporate: await Case.countDocuments({ caseType: "corporate" }),
        cyber: await Case.countDocuments({ caseType: "cyber" }),
        other: await Case.countDocuments({ caseType: "other" }),
      },
      byPriority: {
        low: await Case.countDocuments({ priority: "low" }),
        medium: await Case.countDocuments({ priority: "medium" }),
        high: await Case.countDocuments({ priority: "high" }),
        critical: await Case.countDocuments({ priority: "critical" }),
      },
    };

    res.status(200).json({
      success: true,
      data: stats,
    });
  } catch (error) {
    console.error("❌ Get case stats error:", error);
    res.status(500).json({
      success: false,
      message: "Error retrieving case statistics",
      error: error.message,
    });
  }
};

/**
 * Get evidence upload trend (weekly data for graph)
 * GET /api/cases/dashboard/evidence-trend
 */
const getEvidenceUploadTrend = async (req, res) => {
  try {
    // Get last 4 weeks of data
    const weeks = [];
    const today = new Date();

    // Create array of last 4 weeks' start dates (Monday)
    for (let i = 3; i >= 0; i--) {
      const d = new Date(today);
      d.setDate(d.getDate() - d.getDay() + 1 - i * 7); // Get Monday of each week
      weeks.push({
        startDate: new Date(d),
        weekNumber: i,
      });
    }

    // Get evidence counts for each week
    const trendData = [];
    const weekLabels = ["Week 1", "Week 2", "Week 3", "Week 4"];

    for (let i = 0; i < weeks.length; i++) {
      const currentWeekStart = weeks[i].startDate;
      const nextWeekStart = new Date(currentWeekStart);
      nextWeekStart.setDate(nextWeekStart.getDate() + 7);

      const count = await Evidence.countDocuments({
        createdAt: {
          $gte: currentWeekStart,
          $lt: nextWeekStart,
        },
      });

      trendData.push({
        month: weekLabels[i],
        count: count,
      });
    }

    res.status(200).json({
      success: true,
      data: trendData,
    });
  } catch (error) {
    console.error("❌ Get evidence trend error:", error);
    res.status(500).json({
      success: false,
      message: "Error retrieving evidence trend",
      error: error.message,
    });
  }
};

/**
 * Get recent activity (latest evidence uploads and case updates)
 * GET /api/cases/dashboard/recent-activity
 */
const getRecentActivity = async (req, res) => {
  try {
    const activities = [];

    // Get recent evidence uploads (last 10)
    const recentEvidence = await Evidence.find()
      .populate("uploader", "username")
      .sort({ createdAt: -1 })
      .limit(10);

    // Get recent case updates (last 10)
    const recentCases = await Case.find()
      .select("_id caseNumber title status createdAt updatedAt")
      .sort({ updatedAt: -1 })
      .limit(10);

    // Format evidence uploads as activities
    recentEvidence.forEach((evidence) => {
      const timeAgo = getTimeAgo(evidence.createdAt);
      activities.push({
        id: evidence.evidenceId,
        action: "Evidence Uploaded",
        user: evidence.uploader?.username || "Unknown User",
        time: timeAgo,
        timestamp: evidence.createdAt,
        type: "evidence",
      });
    });

    // Format case updates as activities
    recentCases.forEach((caseItem) => {
      const timeAgo = getTimeAgo(caseItem.updatedAt);
      activities.push({
        id: caseItem.caseNumber,
        action: `Case ${caseItem.status === "closed" ? "Closed" : "Updated"}`,
        user: "System",
        time: timeAgo,
        timestamp: caseItem.updatedAt,
        type: "case",
      });
    });

    // Sort by timestamp (most recent first)
    activities.sort((a, b) => b.timestamp - a.timestamp);

    // Return top 6 most recent activities
    const recentActivities = activities.slice(0, 6);

    res.status(200).json({
      success: true,
      data: recentActivities,
    });
  } catch (error) {
    console.error("❌ Get recent activity error:", error);
    res.status(500).json({
      success: false,
      message: "Error retrieving recent activity",
      error: error.message,
    });
  }
};

/**
 * Helper function to format time difference
 */
function getTimeAgo(date) {
  const now = new Date();
  const seconds = Math.floor((now - date) / 1000);

  if (seconds < 60) return "just now";
  if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)} days ago`;

  return date.toLocaleDateString();
}

export {
  createCase,
  getAllCases,
  getCaseById,
  findSimilarCases,
  updateCase,
  closeCase,
  addTimelineEntry,
  linkEvidence,
  getCaseStats,
  getEvidenceUploadTrend,
  getRecentActivity,
};
