import PDFDocument from "pdfkit";
import { createWriteStream } from "fs";
import { resolve } from "path";
import { mkdir } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate a PDF report for case comparison
 * @param {Object} comparisonData - The comparison data with case details and results
 * @returns {Promise<string>} - Path to the generated PDF file
 */
export const generateComparisonPDF = async (comparisonData) => {
  try {
    const { case1, case2, comparisonResult, similarityScore, generatedAt } =
      comparisonData;

    // Create uploads directory if it doesn't exist
    const uploadsDir = resolve(__dirname, "../uploads/comparisons");
    await mkdir(uploadsDir, { recursive: true });

    // Generate unique filename with timestamp
    const timestamp = Date.now();
    const fileName = `comparison_${case1.caseNumber}_vs_${case2.caseNumber}_${timestamp}.pdf`;
    const filePath = resolve(uploadsDir, fileName);

    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: "A4",
          margin: 50,
          bufferPages: true,
        });

        const stream = createWriteStream(filePath);
        doc.pipe(stream);

        // Title
        doc.fontSize(24).font("Helvetica-Bold").text("Case Comparison Report", {
          align: "center",
        });

        doc
          .fontSize(10)
          .font("Helvetica")
          .text(`Generated on: ${new Date(generatedAt).toLocaleString()}`, {
            align: "center",
          });

        doc.moveDown();

        // Case 1 Header
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Case 1: " + case1.title);

        doc
          .fontSize(10)
          .font("Helvetica")
          .text("Case Number: " + case1.caseNumber)
          .text("Case ID: " + case1.id);

        doc.moveDown();

        // Case 2 Header
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Case 2: " + case2.title);

        doc
          .fontSize(10)
          .font("Helvetica")
          .text("Case Number: " + case2.caseNumber)
          .text("Case ID: " + case2.id);

        doc.moveDown();

        // Similarity Score
        doc
          .fontSize(16)
          .font("Helvetica-Bold")
          .text("Similarity Score: " + similarityScore + "%", {
            fill: getSimilarityColor(similarityScore),
          });

        doc.moveDown(2);

        // Comparison Details
        doc.fontSize(12).font("Helvetica-Bold").text("Detailed Analysis");

        doc.moveDown();

        doc.fontSize(10).font("Helvetica").text(comparisonResult, {
          align: "justify",
          width: 500,
        });

        doc.moveDown(2);

        // Footer
        doc
          .fontSize(8)
          .font("Helvetica")
          .text(
            "This report has been generated by the Forensic Case Management System",
            {
              align: "center",
            },
          );

        // Stream events
        stream.on("finish", () => {
          console.log("✅ PDF generated successfully:", filePath);
          resolve(filePath);
        });

        stream.on("error", (err) => {
          console.error("❌ Stream error:", err);
          reject(err);
        });

        doc.on("error", (err) => {
          console.error("❌ Document error:", err);
          reject(err);
        });

        doc.end();
      } catch (error) {
        console.error("❌ PDF generation error:", error);
        reject(error);
      }
    });
  } catch (error) {
    console.error("❌ Error in generateComparisonPDF:", error);
    throw error;
  }
};

/**
 * Get color for similarity score
 */
function getSimilarityColor(score) {
  if (score >= 75) return "#10b981"; // Green for high similarity
  if (score >= 50) return "#f59e0b"; // Amber for medium similarity
  return "#ef4444"; // Red for low similarity
}

export default {
  generateComparisonPDF,
};
